config/routes.rb
Albumslist::Application.routes.draw do
  resources :album_owneds


  resources :artists


  resources :albums


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/album_owned.rb
class AlbumOwned < ActiveRecord::Base
  self.table_name = "albums_owned"
  attr_accessible :dateacquired, :datewished

  belongs_to :user
  belongs_to :album
end

app/controllers/album_owneds_controller.rb
class AlbumOwnedsController < ApplicationController
  # GET /album_owneds
  # GET /album_owneds.json
  def index
    @album_owneds = AlbumOwned.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @album_owneds }
    end
  end

  # GET /album_owneds/1
  # GET /album_owneds/1.json
  def show
    @album_owned = AlbumOwned.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album_owned }
    end
  end

  # GET /album_owneds/new
  # GET /album_owneds/new.json
  def new
    @album_owned = AlbumOwned.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album_owned }
    end
  end

  # GET /album_owneds/1/edit
  def edit
    @album_owned = AlbumOwned.find(params[:id])
  end

  # POST /album_owneds
  # POST /album_owneds.json
  def create
    @album_owned = AlbumOwned.new(params[:album_owned])

    respond_to do |format|
      if @album_owned.save
        format.html { redirect_to @album_owned, notice: 'Album owned was successfully created.' }
        format.json { render json: @album_owned, status: :created, location: @album_owned }
      else
        format.html { render action: "new" }
        format.json { render json: @album_owned.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /album_owneds/1
  # PUT /album_owneds/1.json
  def update
    @album_owned = AlbumOwned.find(params[:id])

    respond_to do |format|
      if @album_owned.update_attributes(params[:album_owned])
        format.html { redirect_to @album_owned, notice: 'Album owned was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album_owned.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /album_owneds/1
  # DELETE /album_owneds/1.json
  def destroy
    @album_owned = AlbumOwned.find(params[:id])
    @album_owned.destroy

    respond_to do |format|
      format.html { redirect_to album_owneds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/album_owneds_helper.rb
module AlbumOwnedsHelper
end

app/views/album_owneds/_form.html.erb
<%= simple_form_for(@album_owned) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :datewished %>
    <%= f.input :dateacquired %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/album_owneds/edit.html.erb
<h1>Editing album_owned</h1>

<%= render 'form' %>

<%= link_to 'Show', @album_owned %> |
<%= link_to 'Back', album_owneds_path %>

app/views/album_owneds/index.html.erb
<h1>Listing album_owneds</h1>

<table>
  <tr>
    <th>Datewished</th>
    <th>Dateacquired</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @album_owneds.each do |album_owned| %>
  <tr>
    <td><%= album_owned.datewished %></td>
    <td><%= album_owned.dateacquired %></td>
    <td><%= link_to 'Show', album_owned %></td>
    <td><%= link_to 'Edit', edit_album_owned_path(album_owned) %></td>
    <td><%= link_to 'Destroy', album_owned, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album owned', new_album_owned_path %>

app/views/album_owneds/new.html.erb
<h1>New album_owned</h1>

<%= render 'form' %>

<%= link_to 'Back', album_owneds_path %>

app/views/album_owneds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Datewished:</b>
  <%= @album_owned.datewished %>
</p>

<p>
  <b>Dateacquired:</b>
  <%= @album_owned.dateacquired %>
</p>


<%= link_to 'Edit', edit_album_owned_path(@album_owned) %> |
<%= link_to 'Back', album_owneds_path %>